export const SET_MESSAGES = 'SET_MESSAGES',
    SET_LOADED = 'SET_LOADED',
    SEND_MESSAGE = 'SEND_MESSAGE',
    DELETE_MESSAGE = 'DELETE_MESSAGE',
    EDIT_MESSAGE = 'EDIT_MESSAGE',
    LOAD_CHATS = 'LOAD_CHATS'